name: build

on:
  watch: 
   type: started
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v2.2.6
      with:
        lazarus-version: stable
        include-packages: "Synapse 40.1"
    - name: Build the Main Application
      run: lazbuild "Cheat Engine/cheatengine.lpi"
